services:
  postgres:
    image: timescale/timescaledb:2.15.2-pg16
    container_name: energy-postgres-container
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - energy-postgres-volume:/var/lib/postgresql/data
    networks:
      - energy-network
    
volumes:
  energy-postgres-volume:

networks:
  energy-network:
    external: true
    name: energy-network