spring:
  profiles:
#     active: dev # 개발용
    active: prod # 배포용
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
  config: classpath:logback-spring.xml


springdoc:
  swagger-ui:
    # config-url: /v3/api-docs/swagger-config
    path: /docs



# constants
DOMAIN:
  FRONT: ${FRONT_DOMAIN} # http://localhost:5173 형식 (80, 443은 포트 안 써도 됨)
  BACK: ${BACK_DOMAIN} # http://localhost:8080 형식 (80, 443은 포트 안 써도 됨)

secretKeyPlain: ${SECURE_KEY_PLAIN} # 시큐리티 키
